package de.ottoextra.rpnames.model;

public enum RpNameSource {
    SEEN_ONLINE,
    SEEN_TABLIST,
    SEEN_NAMETAG,
    LEARNED_FROM_CHAT,
    LEARNED_FROM_HOVER,
    API_IMPORTED,
    MANUAL_EDIT,
    MIGRATED_FROM_OTTOTALK,
    MIGRATED_FROM_RPNAMES,
    IMPORTED_FROM_OTTOPLUS
}
